[package]
name = "bevy_mod_skinned_aabb"
version = "0.1.0"
edition = "2021"
keywords = ["bevy"]
categories = ["game-engines"]
authors = ["Greeble <greeble@greeble.dev>"]
repository = "https://github.com/greeble-dev/bevy_mod_skinned_aabb"
license = "MIT OR Apache-2.0"

[dependencies]
bevy_math = { version = "0.15", default-features = false }
bevy_mesh = { version = "0.15", default-features = false }
bevy_derive = { version = "0.15", default-features = false }
bevy_ecs = { version = "0.15", default-features = false }
bevy_render = { version = "0.15", default-features = false }
bevy_app = { version = "0.15", default-features = false }
bevy_asset = { version = "0.15", default-features = false }
bevy_transform = { version = "0.15", default-features = false }
bevy_gizmos = { version = "0.15", default-features = false }
bevy_color = { version = "0.15", default-features = false }
bevy_reflect = { version = "0.15", default-features = false }

[dev-dependencies]
bevy = "0.15"

[[example]]
name = "showcase"
