name: CI

on:
    push:
        branches:
            - main
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Run cargo check
              run: cargo check --all-features --all-targets

    lints:
        name: Lints
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Run cargo fmt
              run: cargo fmt --all -- --check
            - name: Run cargo clippy
              run: cargo clippy --all-features --all-targets -- -D warnings
