name: CI

on:
    push:
        branches:
            - main
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    all:
        name: All
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2.7
            - name: Update Packages
              run: sudo apt-get update -yq
            - name: Install dependencies
              run: sudo apt-get install -yq --no-install-recommends libudev-dev libasound2-dev libxcb-composite0-dev
            - name: Run cargo fmt
              run: cargo fmt --all -- --check
            - name: Run cargo clippy
              run: cargo clippy --all-features --all-targets -- -D warnings
            - name: Run cargo check
              run: cargo check --all-features --all-targets
            - name: Run cargo test
              run: cargo test
            - name: Run cargo bench
              run: cargo bench
